#
# This is an example summit project build config
# 
---

name: abl

packages:
  - alpine-base
  - busybox
  - cpio
  - cryptsetup
  - efibootmgr
  - gcompat
  - kbd
  - kexec-tools
  - lvm2
  - mdadm
  - mg
  - ncurses-libs
  - terminus-font
  - util-linux

tasks:
  - name: Apply configuration
    copy:
      src: overlay/.
      dest: /
  - name: Enable mdev at boot
    chroot: rc-update add mdev sysinit
  - name: Copy over the ABL bootmenu binary
    copy:
      src: dist/bootmenu
      dest: /sbin/bootmenu
  - name: Make sure the binary we just copied is executable
    chroot: chmod o+x /sbin/bootmenu

images:
  - initramfs:
      compression: zstd --fast
      dest: initramfs.zstd
